language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -U numpy
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - python -m pytest sense2vec
